name: Python pickle/unpickle test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.5", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: ${{ matrix.python-version }}
          command: python -c "import sys; print(sys.version)"

      - name: Generate example pickle files
        working-directory: ./examples
        run: python generate.py

      - name: Unpickle example files
        working-directory: ./
        run: |
          for f in $(ls examples/*.pkl)
          do
            echo "Unpickling $f"
            python picklevis_core.py $f
          done
